# Build configuration
[build]
  command = "npm run build"
  publish = "dist"

# Secrets scanning configuration
# Firebase client config values are PUBLIC and safe to include in client-side code
# Reference: https://firebase.google.com/docs/projects/api-keys
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_FIREBASE_API_KEY,VITE_FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_PROJECT_ID,VITE_FIREBASE_STORAGE_BUCKET,VITE_FIREBASE_MESSAGING_SENDER_ID,VITE_FIREBASE_APP_ID,VITE_FIREBASE_MEASUREMENT_ID,VITE_MIXPANEL_TOKEN"

# Cache headers for performance
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200